### PR TITLE
Add LaynePeng as fate-operator project owner.

### PR DESCRIPTION
**Pull request by LaynePeng**
Signed-off-by: Layne Peng <playne@vmware.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
Oh CI-bot does not have the write permission.  Ref https://github.com/kubeflow/internal-acls/pull/257

**Comment by LaynePeng** [comment]
> Oh CI-bot does not have the write permission. Ref [kubeflow/internal-acls#257](https://github.com/kubeflow/internal-acls/pull/257)

So we should wait the ticket kubeflow/internal-acls#257 fixed?

**Comment by gaocegege** [comment]
Yeah, I think so.

**Pull request merged**
