### PR TITLE
feat: update CRD to support new KubeFATE

### PR DESCRIPTION
**Pull request by owlet42**
The new version of kubefate uses MySQL instead of mongodb

### CODE REVIEW

**Comment by LaynePeng** [comment]
> Is it ready to review?

I think there will be another CRD need to upgrade? Am I right? @owlet42

**Comment by gaocegege** [comment]
Please resolve the conflicts.

**Comment by gaocegege** [comment]
Can we merge it?

Please leaver a `/approve `

**Comment by gaocegege** [comment]
https://github.com/kubeflow/fate-operator/pull/27/files

There is no change in the PR, should we close it?

**Comment by LaynePeng** [comment]
> https://github.com/kubeflow/fate-operator/pull/27/files
> 
> There is no change in the PR, should we close it?

@owlet42 I am confuse, why this PR no change?

**Pull request closed without merging**
