### PR TITLE
Fixes #31 - containers now run as nonroot.

### LINKED ISSUE #31: Support restrictive pod security policy.
Currently all containers fail to run with restricted (nonroot) pod security policies.

### PR DESCRIPTION
**Pull request by tdhite**

### CODE REVIEW

**Comment by tdhite** [comment]
We're getting the CLA in place -- just not working as planned. Please stand by.

**Comment by LaynePeng** [comment]
> We're getting the CLA in place -- just not working as planned. Please stand by.

Sure. Will wait.

**Comment by owlet42** [comment]
Considering the safety of pod operation.
Could we add in the manifests `allowPrivilegeEscalation: false`?

**Comment by tdhite** [comment]
I can add/rebase that in. Still waiting on our CCLA process to work (sigh).

At the same time, might as well switch to "runAsNonRoot: true" versus runAs specs. I'll do that at the same time.

**Comment by tdhite** [comment]
@googlebot I signed it!

**Review by LaynePeng — APPROVED** [review]
/lgtm

**Pull request merged**
